# ~/.aerospace.toml

# ==========================================
# 1. ГЛОБАЛЬНЫЕ НАСТРОЙКИ 
# (Должны быть строго до любых [секций])
# ==========================================



# Запускаем Sketchybar вместе с AeroSpace
after-startup-command = ['exec-and-forget sketchybar']

# Триггер для обновления воркспейсов в Sketchybar
exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE']

start-at-login = true 
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Авто-фокус мышки
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true


# ==========================================
# 2. СЕКЦИИ НАСТРОЕК
# ==========================================

# Внешний вид сетки (зазоры между окнами)
[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top    = [{ monitor.main = 35 }, { monitor.secondary = 12 }, 8]
    outer.right =      8

[workspace-to-monitor-force-assignment]
1 = 'main'       # Воркспейс 1 всегда на главном мониторе (экран макбука или основной дисплей)
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'  # Воркспейс 6 всегда на втором мониторе
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
10 = 'secondary'

# ==========================================
# 3. БИНДИНГИ (ХОТКЕИ)
# ==========================================
[mode.main.binding]

# --- Запуск приложений ---
alt-q = 'exec-and-forget open -n -a Ghostty'
alt-b = 'exec-and-forget open -a Arc'
alt-e = 'exec-and-forget open -a Finder'


# ПОЛНОЕ УБИЙСТВО ПРИЛОЖЕНИЯ (Quit), а не просто закрытие окна
alt-c = 'exec-and-forget osascript -e "tell application \"System Events\" to keystroke \"q\" using command down"'

alt-m = 'fullscreen'
alt-shift-space = 'layout floating tiling' # переключение плавающего режима


# --- Воркспейсы (1-10) ---
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# --- Перенос окон на воркспейсы с автоматическим переключением ---
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']
