set -g prefix C-a
unbind C-b
bind C-a send-prefix

setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set -g base-index 1
setw -g pane-base-index 1

set -g status-style "bg=default,fg=#f5c2e7"
set -g status-left-length 50
set -g status-left "#[fg=#b4befe,bold]   #S "
set -g status-right "#[fg=#f5c2e7,bold] %H:%M "

setw -g window-status-current-format "#[fg=#1e1e2e,bg=#f5c2e7,bold] #I:#W "
setw -g window-status-format "#[fg=#9399b2,bg=default] #I:#W "

set -g pane-active-border-style "fg=#f5c2e7"
set -g pane-border-style "fg=#45475a"

set -g message-style "fg=#1e1e2e,bg=#f5c2e7,bold"
set -g default-command /run/current-system/sw/bin/fish
set -g default-shell /run/current-system/sw/bin/fish
